from .adjoint import (
    FrozenStepAdjointResult,
    LaggedMidpointRolloutAdjointResult,
    LaggedMidpointStepAdjointResult,
    RungeKutta4RolloutAdjointResult,
    RungeKutta4StepAdjointResult,
    exact_frozen_step_adjoint,
    lagged_midpoint_rollout_adjoint,
    lagged_midpoint_step_adjoint,
    lagged_midpoint_step_with_history,
    runge_kutta4_rollout_adjoint,
    runge_kutta4_step_adjoint,
    runge_kutta4_step_with_stages,
    runge_kutta4_substep_rollout_adjoint,
)
from .data import (
    ContinuousBatch,
    ContinuousDataset,
    ContinuousSample,
    SampleManifest,
    batch_samples,
    linear_interpolate,
    load_manifest_npz,
    load_sample_npz,
    save_manifest_npz,
    save_sample_npz,
    slice_batch,
    split_manifest,
)
from .decoders import QuadraticReadoutDecoder, decoder_loss_and_state_grad
from .dynamics import QuadraticDynamics
from .distributed import DistributedReducedObjective, distributed_rank, distributed_world_size
from .linear import DenseLinearA, DissipativeSkewA, LinearOperatorA
from .microbatch import MicroBatchReducedObjective
from .quadratic import DenseQuadratic, EnergyDenseQuadratic, EnergyTuckerTTQuadratic, SkewCPQuadratic, TuckerTTQuadratic
from .reduced import ReducedObjective, ReducedObjectiveResult, trapezoidal_weights, weighted_trajectory_mse
from .source import LinearSource, ZeroSource
from .steppers import (
    AdaptiveDefectConfig,
    DenseLaggedMidpointStepper,
    DensePicardRolloutResult,
    DenseRolloutResult,
    ExactSMWLaggedMidpointStepper,
    RungeKutta4Stepper,
    SubstepRungeKutta4Stepper,
    SkewCPDefectLaggedMidpointStepper,
    exact_frozen_smw_solve,
)
from .training import (
    JsonlOptimizationLogger,
    LBFGSReducedTrainer,
    LBFGSTrainingResult,
    OptimizationRecord,
    dynamics_grad_norm,
    objective_backend_metadata,
)
from .varpro import DecoderNormalSolveResult, DecoderNormalTerms, assemble_decoder_normal_terms, solve_decoder_normal_equation, solve_decoder_normal_terms

__all__ = [
    "AdaptiveDefectConfig",
    "ContinuousBatch",
    "ContinuousDataset",
    "ContinuousSample",
    "DenseLaggedMidpointStepper",
    "DensePicardRolloutResult",
    "DenseLinearA",
    "DenseQuadratic",
    "DenseRolloutResult",
    "DecoderNormalSolveResult",
    "DissipativeSkewA",
    "DistributedReducedObjective",
    "ExactSMWLaggedMidpointStepper",
    "EnergyDenseQuadratic",
    "EnergyTuckerTTQuadratic",
    "FrozenStepAdjointResult",
    "JsonlOptimizationLogger",
    "LaggedMidpointRolloutAdjointResult",
    "LaggedMidpointStepAdjointResult",
    "LBFGSReducedTrainer",
    "LBFGSTrainingResult",
    "LinearOperatorA",
    "LinearSource",
    "MicroBatchReducedObjective",
    "OptimizationRecord",
    "QuadraticDynamics",
    "QuadraticReadoutDecoder",
    "ReducedObjective",
    "ReducedObjectiveResult",
    "RungeKutta4Stepper",
    "SubstepRungeKutta4Stepper",
    "RungeKutta4RolloutAdjointResult",
    "RungeKutta4StepAdjointResult",
    "SampleManifest",
    "SkewCPDefectLaggedMidpointStepper",
    "SkewCPQuadratic",
    "TuckerTTQuadratic",
    "ZeroSource",
    "batch_samples",
    "decoder_loss_and_state_grad",
    "exact_frozen_smw_solve",
    "exact_frozen_step_adjoint",
    "lagged_midpoint_rollout_adjoint",
    "lagged_midpoint_step_adjoint",
    "lagged_midpoint_step_with_history",
    "runge_kutta4_rollout_adjoint",
    "runge_kutta4_step_adjoint",
    "runge_kutta4_step_with_stages",
    "runge_kutta4_substep_rollout_adjoint",
    "linear_interpolate",
    "load_manifest_npz",
    "load_sample_npz",
    "save_manifest_npz",
    "save_sample_npz",
    "slice_batch",
    "solve_decoder_normal_equation",
    "solve_decoder_normal_terms",
    "assemble_decoder_normal_terms",
    "DecoderNormalTerms",
    "split_manifest",
    "trapezoidal_weights",
    "dynamics_grad_norm",
    "distributed_rank",
    "distributed_world_size",
    "weighted_trajectory_mse",
]
